# Generated by Django 3.0.5 on 2020-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Empty', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article', max_length=120),
        ),
    ]
